async page => {
  const check=(condition,message)=>{if(!condition)throw new Error(message);};
  const context=await page.context().browser().newContext({viewport:{width:1440,height:1000}}),p=await context.newPage(),errors=[];
  p.on('pageerror',e=>errors.push(e.message));
  try {
    await p.goto('http://127.0.0.1:5000/?emulators#/characters');
    await p.getByRole('button',{name:'Create PC',exact:true}).click();
    await p.locator('[data-field="name"]').waitFor();
    check(await p.locator('[data-public]').count()===7,'Seven section privacy controls missing');
    check(!await p.locator('[data-public="abilities"]').isChecked(),'Abilities default public');
    check((await p.locator('.creator-overview').innerText()).includes('Creation'),'New character not in Creation');
    check(await p.getByRole('heading',{name:'Creation review',exact:true}).count()===0,'Creation review card remains');
    check(await p.locator('#creator-summary').count()===1,'Character summary removed');
    check(await p.locator('[data-action="reset-section"]').count()===7,'Creation section reset controls missing');
    const characterId=await p.evaluate(()=>CharacterBuilder.list()[0].id);
    await p.locator('[data-field="startingXP"]').fill('65');await p.locator('[data-field="startingXP"]').blur();
    check((await p.locator('.creator-overview').innerText()).includes('XP 65'),'Starting XP budget did not update');
    await p.evaluate(()=>window.confirm=()=>false);
    await p.locator('[data-action="reset-section"][data-section="summary"]').click();
    check(await p.locator('[data-field="startingXP"]').inputValue()==='65','Cancel reset changed the budget');
    await p.evaluate(()=>window.confirm=()=>true);
    await p.locator('[data-action="reset-section"][data-section="summary"]').click();
    check(await p.locator('[data-field="startingXP"]').inputValue()==='40','Summary reset did not restore starting XP');
    await p.locator('[data-field="name"]').fill('Identity to reset');
    await p.locator('[data-action="reset-section"][data-section="identity"]').click();
    check(await p.locator('[data-field="name"]').inputValue()==='','Identity reset did not clear inputs');
    check(await p.evaluate(()=>CharacterBuilder.list()[0].id)===characterId,'Reset replaced the character ID');
    check(!await p.locator('[data-public="abilities"]').isChecked(),'Reset changed privacy');
    await p.locator('[data-field="name"]').fill('Character browser test');
    await p.locator('[data-field="notes"]').fill('Story to reset');
    await p.locator('[data-action="reset-section"][data-section="story"]').click();
    check(await p.locator('[data-field="notes"]').inputValue()==='','Story reset did not clear inputs');
    check(await p.locator('[data-field="name"]').inputValue()==='Character browser test','Story reset affected Identity');
    await p.getByRole('button',{name:'Begin play',exact:true}).click();
    await p.getByRole('alert').waitFor();
    check((await p.locator('#creator-identity .creator-validation').innerText()).includes('Choose a starting school'),'Missing school guidance is not in Identity');
    check(await p.locator('.creator-exceptions,.creator-creation-options').count()===0,'Generic exceptions menu remains');
    await p.getByRole('button',{name:'Save PC',exact:true}).click();
    await p.waitForURL(/#\/characters$/);await p.getByRole('heading',{name:'Character browser test',exact:true}).waitFor();
    await p.getByRole('button',{name:'Edit',exact:true}).click();
    await p.locator('[data-field="clan"]').selectOption('Crab');
    await p.locator('[data-field="family"]').selectOption('Hida');
    const school=await p.evaluate(async()=>{const c=await(await fetch('public/character-data.json')).json();return c.clans.find(c=>c.name==='Crab').schools.find(s=>s.name==='Hida Bushi');});
    await p.locator('[data-field="school"]').selectOption(school.slug+'#'+school.anchor);
    await p.locator('[data-choice-index="0"]').fill('Battle');await p.locator('[data-choice-index="0"]').blur();
    for(const [i,e]of school.equipment.entries())if(e.choice){await p.locator('[data-equipment-choice="'+i+'"]').fill(/armor/i.test(e.name)?'Light Armor':'Tetsubo');await p.locator('[data-equipment-choice="'+i+'"]').blur();}
    await p.getByRole('button',{name:'Increase Strength for 16 XP',exact:true}).click();
    await p.locator('[data-action="reset-section"][data-section="traits"]').click();
    check(await p.getByRole('button',{name:'Increase Strength for 16 XP',exact:true}).count()===1,'Traits reset did not retain school/family benefits');
    await p.getByRole('button',{name:'Increase Defense for 2 XP',exact:true}).click();
    await p.locator('[data-action="reset-section"][data-section="skills"]').click();
    check(await p.locator('[data-choice-index="0"]').inputValue()==='','Skills reset did not clear selectable grants');
    await p.locator('[data-choice-index="0"]').fill('Battle');await p.locator('[data-choice-index="0"]').blur();
    await p.locator('.creator-later-training > summary').click();
    await p.locator('#training-school').fill('Crab Defender · path');
    await p.getByRole('button',{name:'Add training',exact:true}).click();
    check(await p.locator('[data-action="remove-training"]').count()===1,'First creation path cannot be removed');
    await p.locator('[data-action="remove-training"]').click();
    check(await p.locator('[data-action="remove-training"]').count()===0,'Creation path was not removed');
    await p.locator('#advantage-select').selectOption('Large');await p.getByRole('button',{name:'Add',exact:true}).first().click();
    await p.locator('[data-action="reset-section"][data-section="options"]').click();
    check(await p.locator('output[data-kind="advantage"]').count()===0,'Options reset did not clear advantages');
    await p.locator('#advantage-select').selectOption('Large');await p.getByRole('button',{name:'Add',exact:true}).first().click();
    check(await p.locator('output[data-kind="advantage"]').innerText()==='3','Clan discount not shown in editor');
    await p.getByRole('button',{name:'Increase Large cost',exact:true}).click();
    check(await p.locator('output[data-kind="advantage"]').innerText()==='4','Advantage plus button did not update cost');
    await p.getByRole('button',{name:'Decrease Large cost',exact:true}).click();
    check(await p.locator('output[data-kind="advantage"]').innerText()==='3','Advantage minus button did not restore cost');
    const skillRow=p.locator('.creator-skill-row').filter({has:p.getByRole('combobox',{name:'Roll trait for Heavy Weapons',exact:true})});
    check(await skillRow.getAttribute('data-ring')==='Water','Strength skill does not use Water tint');
    await p.getByRole('combobox',{name:'Roll trait for Heavy Weapons',exact:true}).selectOption('Agility');
    check(await skillRow.getAttribute('data-ring')==='Fire','Skill tint did not follow selected trait');
    await p.getByRole('combobox',{name:'Roll trait for Heavy Weapons',exact:true}).selectOption('Strength');
    await p.getByRole('button',{name:'Increase Reflexes for 12 XP',exact:true}).click();
    await p.getByRole('button',{name:'Increase Heavy Weapons for 2 XP',exact:true}).click();
    await p.getByRole('button',{name:'Increase Heavy Weapons for 3 XP',exact:true}).click();
    const heavy=p.locator('.creator-skill-row').filter({has:p.locator('strong').filter({hasText:/^Heavy Weapons$/})});
    await heavy.locator('summary').click();
    await p.locator('[data-emphasis-name="Heavy Weapons"]').fill('Tetsubo');
    await heavy.getByRole('button',{name:'Buy emphasis · 2 XP',exact:true}).click();
    check(!await p.locator('.creator-validation').count(),'Valid sheet has unresolved creation violations');
    await p.locator('[data-equipped="school:0"]').check();
    const weaponIndex=school.equipment.findIndex(e=>/Heavy Weapon/i.test(e.name));
    await p.locator('[data-equipped="school:'+weaponIndex+'"]').check();
    await p.locator('[data-field="notes"]').fill('OWNER PRIVATE NOTES\nSecond line');
    const editorURL=p.url();
    await p.getByRole('link',{name:'View family ↗',exact:true}).click();
    await p.getByRole('dialog').waitFor();
    check(p.url()===editorURL,'Rule popup navigated away from editor');
    check((await p.locator('.rules-popup-body').innerText()).includes('Hida'),'Family rule reference missing');
    await p.locator('.rules-popup .inline-contents > summary').click();
    await p.locator('.rules-popup .inline-contents a').first().click();
    check(p.url()===editorURL,'Popup contents link navigated away from editor');
    await p.keyboard.press('Escape');
    await p.getByRole('dialog').waitFor({state:'hidden'});
    await p.waitForFunction(()=>document.querySelector('.rules-popup-body').childElementCount===0);
    check(await p.locator('[data-field="notes"]').inputValue()==='OWNER PRIVATE NOTES\nSecond line','Popup discarded pending notes');
    if(!await p.locator('#custom-ability-name').isVisible())await p.getByText('Custom ability',{exact:true}).click();
    await p.locator('#custom-ability-name').fill('OWNER PRIVATE POWER');
    await p.locator('#custom-ability-description').fill('OWNER PRIVATE POWER DESCRIPTION');
    await p.getByRole('button',{name:'Add custom ability',exact:true}).click();
    await p.locator('[data-action="reset-section"][data-section="abilities"]').click();
    check(!(await p.locator('#creator-abilities').innerText()).includes('OWNER PRIVATE POWER'),'Abilities reset did not clear selections');
    if(!await p.locator('#custom-ability-name').isVisible())await p.getByText('Custom ability',{exact:true}).click();
    await p.locator('#custom-ability-name').fill('OWNER PRIVATE POWER');
    await p.locator('#custom-ability-description').fill('OWNER PRIVATE POWER DESCRIPTION');
    await p.getByRole('button',{name:'Add custom ability',exact:true}).click();
    for(const width of [1440,390]) {
      await p.setViewportSize({width,height:900});
      check(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Character editor overflows at '+width);
      check(await p.locator('[data-action="section"][data-section="abilities"]').isVisible(),'Abilities navigation missing');
      await p.screenshot({path:'output/playwright/character-'+width+'.png',fullPage:true});
      await p.getByRole('link',{name:'Creation rules ↗',exact:true}).click();
      await p.getByRole('dialog').waitFor();
      check(await p.evaluate(()=>document.querySelector('.rules-popup').getBoundingClientRect().right<=innerWidth),'Rules popup overflows at '+width);
      await p.getByRole('button',{name:'Close rules',exact:true}).click();
    }
    await p.getByRole('button',{name:'Begin play',exact:true}).click();
    check((await p.locator('.creator-overview').innerText()).includes('Advancement'),'Begin play did not transition');
    check(await p.locator('[data-action="reset-section"]').count()===0,'Section reset controls shown during Advancement');
    await p.getByRole('button',{name:'Advance Hida Bushi school rank',exact:true}).click();
    check((await p.locator('.creator-overview').innerText()).includes('School Rank 2'),'School rank did not advance');
    await p.getByRole('button',{name:'Decrease Hida Bushi school rank',exact:true}).click();
    check((await p.locator('.creator-overview').innerText()).includes('School Rank 1'),'School rank correction failed');
    await p.locator('#xp-award').fill('100');await p.locator('#xp-reason').fill('PRIVATE HISTORY EXPLANATION');
    await p.getByRole('button',{name:'Record XP',exact:true}).click();
    await p.getByRole('button',{name:'Increase Reflexes for 16 XP',exact:true}).click();
    await p.getByRole('button',{name:'Increase Reflexes for 20 XP',exact:true}).click();
    check(await p.getByRole('button',{name:'Increase Reflexes for 24 XP',exact:true}).isEnabled(),'Advancement rank still capped at 4');
    await p.getByRole('button',{name:'Decrease Reflexes',exact:true}).click();
    const downloadPromise=p.waitForEvent('download');await p.getByRole('button',{name:'Export JSON ↗',exact:true}).click();
    const downloaded=await downloadPromise;const stream=await downloaded.createReadStream();let json='';for await(const part of stream)json+=part;
    const exported=JSON.parse(json);
    check(exported.character.phase==='advancement','Export phase missing');
    check(exported.character.startingXP===40,'Starting XP not exported');
    check(exported.character.progression.history.some(e=>e.kind==='refund'&&e.amount===-20),'Refund not recorded at paid cost');
    check(exported.character.progression.history.some(e=>e.explanation==='PRIVATE HISTORY EXPLANATION'),'XP award not retained');
    check(exported.derived.combat.armorTN===30,'Equipped armor not calculated');
    await p.emulateMedia({media:'print'});
    check(await p.locator('.creator-print-sheet').isVisible(),'Owner print missing');
    check((await p.locator('.creator-print-sheet').innerText()).includes('OWNER PRIVATE POWER'),'Owner abilities missing from print');
    await p.emulateMedia({media:'screen'});
    await p.getByRole('button',{name:'Save PC',exact:true}).click();await p.waitForURL(/#\/characters$/);
    await p.reload();await p.getByRole('button',{name:'Edit',exact:true}).click();
    check((await p.locator('.creator-overview').innerText()).includes('Advancement'),'Offline phase/history lost on reload');
    check(await p.locator('[data-field="notes"]').inputValue()==='OWNER PRIVATE NOTES\nSecond line','Offline notes lost');
    check(errors.length===0,'Browser errors: '+errors.join('; '));
    return 'Character browser checks passed: editable starting XP, seven creation resets, rule popups, signed-out drafts, validation, Begin play, payments/refunds, desktop/mobile, privacy, print/export and reload.';
  } finally {await context.close();}
}
