async page => {
  // Run with playwright-cli run-code --filename scripts/browser_checks.js.
  // Requires the emulator Google account to be signed in on the active page.
  const check = (condition,message) => {if(!condition)throw new Error(message);};
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  for (const c of page.context().browser().contexts()) if (c !== page.context()) await c.close();
  await page.goto('http://127.0.0.1:5000/?emulators#/campaigns');
  await page.getByRole('button',{name:'Create campaign',exact:true}).waitFor();
  await page.evaluate(()=>{window.prompt=()=> 'Browser campaign';window.confirm=()=>true;});

  await page.getByRole('button',{name:'Create campaign',exact:true}).click();
  await page.locator('[data-campaign-field="title"]').waitFor();
  const campaignURL=page.url();
  await page.getByRole('button',{name:'+ Session',exact:true}).click();
  await page.locator('[data-campaign-field="session-title"]').fill('Session One');
  const notes='\nLine one\n\n'+('A long session note. '.repeat(4000))+'\nLast line';
  await page.locator('[data-campaign-field="session-text"]').fill(notes);
  await page.getByRole('heading',{name:'Sessions',exact:true}).click();
  await page.waitForFunction(()=>window.CampaignStorage.status==='Saved to campaign').catch(e=>{throw new Error('Autosave did not complete: '+e.message);});
  await page.reload();
  await page.locator('[data-campaign-field="session-text"]').waitFor();
  check(await page.locator('[data-campaign-field="session-text"]').inputValue()===notes,'Session autosave changed line breaks');
  await page.getByRole('button',{name:'+NPC',exact:true}).click();
  await page.locator('[data-campaign-field="npc-name"]').fill('Hidden NPC');
  await page.locator('[data-campaign-field="npc-notes"]').fill('GM-only notes');
  await page.getByRole('heading',{name:'NPCs',exact:true}).click();
  await page.getByRole('button',{name:'+PC',exact:true}).click();
  await page.getByRole('button',{name:'Create PC',exact:true}).click();
  await page.locator('[data-field="name"]').waitFor();
  await page.locator('[data-field="name"]').fill('GM Personal PC');
  check(await page.locator('[data-public]').count()===6,'Six privacy controls missing');
  await page.locator('[data-field="notes"]').fill('HIDDEN OWNER NOTES');
  await page.getByRole('link',{name:'← Campaign',exact:true}).click();
  await page.getByRole('button',{name:'Create invite link',exact:true}).click();
  await page.getByLabel('Invite link', {exact:true}).waitFor();
  const inviteURL=await page.getByLabel('Invite link',{exact:true}).inputValue();
  const browser=page.context().browser();
  const playerContext=await browser.newContext({viewport:{width:390,height:844}});
  const player=await playerContext.newPage();player.on('pageerror',e=>errors.push(e.message));
  await player.goto(inviteURL);
  await player.waitForFunction(()=>window.CampaignStorage && document.getElementById('account-sign-in')?.disabled===false);
  await player.evaluate(async()=>{
    const sdk=await import('https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js');
    await sdk.createUserWithEmailAndPassword(sdk.getAuth(),'player-'+Date.now()+'@example.test','test-password-123');
  });
  await player.getByRole('button',{name:'Join campaign',exact:true}).waitFor();
  check((await player.locator('#navigation a').count())===3,'Mobile tabs are missing');
  await player.getByRole('button',{name:'Join campaign',exact:true}).click();
  await player.getByRole('heading',{name:'PC roster',exact:true}).waitFor();
  check(await player.getByRole('heading',{name:'NPCs',exact:true}).count()===0,'NPCs leaked to player');
  check(await player.locator('[data-campaign-field="session-text"]').getAttribute('readonly')!==null,'Player can edit sessions');
  await player.getByRole('button',{name:'View',exact:true}).click();
  await player.locator('.shared-sheet h2').waitFor();
  check(!(await player.locator('.shared-sheet').innerText()).includes('HIDDEN OWNER NOTES'),'Hidden notes leaked');
  await player.emulateMedia({media:'print'});
  check(!(await player.locator('.shared-sheet').innerText()).includes('HIDDEN OWNER NOTES'),'Hidden notes in print');
  await player.emulateMedia({media:'screen'});
  const downloadPromise=player.waitForEvent('download');
  await player.getByRole('button',{name:'Export JSON',exact:true}).click();
  const download=await downloadPromise;const stream=await download.createReadStream();let exported='';for await(const b of stream)exported+=b;
  check(!exported.includes('HIDDEN OWNER NOTES')&&!exported.includes('sheetJson'),'Full fields leaked in player export');
  await player.getByRole('button',{name:'Close',exact:true}).click();
  const ownerPC = await page.evaluate(()=>CampaignStorage.list('campaigns/'+location.hash.slice(12)+'/pcs/').find(pc=>pc.ownerUid===CampaignStorage.uid));
  await page.locator('[data-campaign="pc-open"][data-id="'+ownerPC.id+'"]').click();
  await page.locator('[data-public="identity"]').uncheck();
  await page.waitForFunction(()=>CharacterStorage.status==='Saved to your account');
  await page.getByRole('link',{name:'← Campaign',exact:true}).click();
  await player.waitForFunction(()=>document.querySelector('#app').textContent.includes('Private PC')&&!document.querySelector('#app').textContent.includes('GM Personal PC'));
  await player.getByRole('button',{name:'View',exact:true}).click();
  await player.getByText('This PC has no public sections.',{exact:true}).waitFor();
  await player.getByRole('button',{name:'Close',exact:true}).click();
  await page.locator('[data-campaign="pc-open"][data-id="'+ownerPC.id+'"]').click();
  await page.locator('[data-public="identity"]').check();
  await page.waitForFunction(()=>CharacterStorage.status==='Saved to your account');
  await page.getByRole('link',{name:'← Campaign',exact:true}).click();
  await player.getByRole('button',{name:'+PC',exact:true}).click();
  await player.getByRole('button',{name:'Create PC',exact:true}).click();
  await player.locator('[data-field="name"]').waitFor();
  await player.locator('[data-field="name"]').fill('Player PC');
  await player.locator('[data-field="notes"]').fill('PLAYER PRIVATE NOTES');
  await player.getByRole('link',{name:'← Campaign',exact:true}).click();
  await page.reload();await page.getByRole('heading',{name:'PC roster',exact:true}).waitFor();
  await page.waitForFunction(()=>document.querySelector('#app').textContent.includes('Player PC')).catch(e=>{throw new Error('GM roster did not update: '+e.message);});
  const row=page.locator('.roster-row').filter({hasText:'Player PC'});
  await row.getByRole('button',{name:'Edit',exact:true}).click();
  await page.locator('#campaign-editor [data-field="name"]').waitFor();
  check(await page.locator('#campaign-editor [data-field="notes"]').inputValue()==='PLAYER PRIVATE NOTES','GM full sheet unavailable');
  check(await page.locator('#campaign-editor [data-public]:disabled').count()===6,'GM can change privacy');
  await page.locator('#campaign-editor [data-field="name"]').fill('Live GM Edit');
  await page.locator('#campaign-editor h1').click();
  await page.waitForFunction(()=>window.CampaignStorage.status==='Saved to campaign').catch(e=>{throw new Error('Autosave did not complete: '+e.message);});
  await player.waitForFunction(()=>window.CharacterBuilder.list().some(c=>c.name==='Live GM Edit')).catch(e=>{throw new Error('GM edit did not reach owner: '+e.message);});
  await player.getByRole('link',{name:'Characters',exact:true}).click();
  await player.getByRole('heading',{name:'Live GM Edit',exact:true}).waitFor();
  await page.goto(campaignURL);
  await page.getByRole('heading',{name:'PC roster',exact:true}).waitFor();
  await page.getByRole('button',{name:'Revoke invite',exact:true}).click();
  await page.getByRole('button',{name:'Create invite link',exact:true}).waitFor();
  await page.waitForFunction(()=>document.querySelector('[data-campaign=invite]')?.disabled===false);
  await player.goto(inviteURL);
  await player.getByText('This invitation has expired or was revoked.',{exact:true}).waitFor();
  await player.goto(campaignURL);await player.getByRole('heading',{name:'PC roster',exact:true}).waitFor();
  await player.evaluate(()=>window.confirm=()=>true);await player.getByRole('button',{name:'Leave campaign',exact:true}).click();
  await player.getByRole('heading',{name:'Campaigns',exact:true}).waitFor();
  await player.getByRole('link',{name:'Characters',exact:true}).click();
  await player.getByRole('heading',{name:'Live GM Edit',exact:true}).waitFor();
  await page.getByRole('link',{name:'Books',exact:true}).click();
  await page.getByRole('heading',{name:'Books',exact:true}).waitFor();
  check(await page.locator('.books-grid > section').count()===5,'Books list missing');
  await page.goto('http://127.0.0.1:5000/?emulators#/combat');
  await page.locator('.article h1').first().waitFor();
  check(await page.locator('.article-content a[href^="#/"]').count()>0,'Local article links removed');
  check(!/Last Haiku|lasthaiku/i.test(await page.locator('body').innerHTML()),'Source branding is rendered');
  await page.getByRole('button',{name:'Search',exact:true}).click();
  await page.locator('#search-input').fill('combat');await page.locator('.search-result').first().waitFor();
  await page.getByRole('button',{name:'Close search',exact:true}).click();
  await page.setViewportSize({width:390,height:844});
  await page.getByRole('link',{name:'Books',exact:true}).click();
  await page.getByRole('heading',{name:'Books',exact:true}).waitFor();
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile page overflows');
  await page.goto('http://127.0.0.1:5000/?emulators#/start');
  await page.waitForURL(/#\/campaigns$/);
  check(errors.length===0,'Browser errors: '+errors.join('; '));
  await playerContext.close();
  return 'Browser checks passed: navigation, books, old articles, mobile, autosave, invites, linking, privacy, print/export, NPCs, GM editing, live updates and leaving.';
}
