const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {randomUUID}=require('node:crypto');
const {initializeTestEnvironment,assertFails}=require('@firebase/rules-unit-testing');
const sdk=require('firebase/firestore');
test('campaign service CRUD, invitation replacement, linking, editing, leaving and deletion',{timeout:20000},async()=>{
 const env=await initializeTestEnvironment({projectId:'demo-l5r-rules-service-tests',firestore:{host:'127.0.0.1',port:8080,rules:fs.readFileSync('firestore.rules','utf8')}});
 const gmDB=env.authenticatedContext('gm').firestore(),aliceDB=env.authenticatedContext('alice').firestore(),bobDB=env.authenticatedContext('bob').firestore();
 const sheet={name:'Alice PC',notes:'PRIVATE',visibility:{identity:true,traits:false,skills:false,options:false,story:false,summary:false}};
 const sections=s=>({identity:{name:s.name},traits:{},skills:{},options:{},story:{notes:s.notes},summary:{}});
 global.window={CharacterStorage:{records:()=>[{id:'pc',sheet,updatedAt:'now'}]},SheetSharing:{encode:async(s,updatedAt)=>{
  const full={sheetJson:JSON.stringify(s),updatedAt,revision:randomUUID(),visibility:s.visibility,sections:sections(s)};
  return {full,public:{revision:full.revision,sections:Object.fromEntries(Object.entries(full.sections).filter(([k])=>s.visibility[k]))}};
 }}};
 const {createCampaignBackend}=await import('../campaign-service.js');
 const gm=createCampaignBackend(gmDB,sdk,'gm','Game Master'),alice=createCampaignBackend(aliceDB,sdk,'alice','Alice'),bob=createCampaignBackend(bobDB,sdk,'bob','Bob');
 let stop;
 try {
  await env.clearFirestore();
  let received;const loaded=new Promise(resolve=>received=resolve);
  stop=gm.subscribe({index(){},receive(path,data){if(/^campaigns\/[^/]+$/.test(path)&&data)received(data);},revoked(){},error(e){throw e;}});
  const c=await gm.create('Service campaign');
  assert.equal((await loaded).title,'Service campaign');
  await gm.write(`campaigns/${c}`,{title:'Renamed',gmUid:'gm'});
  const token=await gm.invite(c);await alice.join(token);assert.equal(await alice.join(token),c);
  assert.equal((await gm.get(`campaigns/${c}/members/gm`)).displayName,'Game Master');
  assert.equal((await gm.get(`campaigns/${c}/members/alice`)).displayName,'Alice');
  await sdk.updateDoc(sdk.doc(aliceDB,`campaigns/${c}/members/alice`),{displayName:sdk.deleteField()});
  await alice.syncPlayerName(c);
  assert.equal((await gm.get(`campaigns/${c}/members/alice`)).displayName,'Alice');
  await alice.saveCharacter('alice','pc',sheet,'now');
  const pcId=await alice.link(c,'pc');
  await gm.write(`campaigns/${c}/sessions/s`,{title:'Session',text:'a\n\nb',updatedAt:'now'});
  await gm.write(`campaigns/${c}/npcs/n`,{name:'NPC',notes:'SECRET',updatedAt:'now'});
  assert.equal((await alice.get(`campaigns/${c}/sessions/s`)).text,'a\n\nb');
  await assertFails(alice.get(`campaigns/${c}/npcs/n`));
  const replacement=await gm.invite(c);
  await assertFails(bob.invitation(token));
  await bob.join(replacement);
  const watch=(backend,full,campaign=c,pc=pcId)=>new Promise(async(resolve,reject)=>{let unsubscribe;try{unsubscribe=await backend.watchSheet(campaign,pc,full,data=>{if(data){resolve(data);queueMicrotask(()=>unsubscribe?.());}},reject);}catch(e){reject(e);}});
  const publicDoc=await watch(bob,false);assert.ok(!JSON.stringify(publicDoc).includes('PRIVATE'));
  const secondCampaign=await alice.create('Another campaign');
  await gm.join(await alice.invite(secondCampaign));
  const secondRef=await alice.link(secondCampaign,'pc');
  assert.equal((await gm.get(`campaigns/${secondCampaign}/pcs/${secondRef}`)).characterId,'pc');
  const fullDoc=await watch(gm,true);assert.ok(fullDoc.sheetJson.includes('PRIVATE'));
  await watch(gm,false,secondCampaign,secondRef);
  assert.ok((await gm.get('users/alice/characters/pc')).sheetJson.includes('PRIVATE'));
  await gm.saveCharacter('alice','pc',{...sheet,name:'GM edit'},'later');
  assert.equal(JSON.parse((await alice.get('users/alice/characters/pc')).sheetJson).name,'GM edit');
  assert.equal((await gm.get(`campaigns/${secondCampaign}/pcs/${secondRef}`)).characterId,'pc');
  await alice.deleteCampaign(secondCampaign);
  assert.ok(await alice.get('users/alice/characters/pc'));
  await gm.write(`campaigns/${c}/pcs/${pcId}`,null);
  await assertFails(gm.get('users/alice/characters/pc'));
  const newPCId=await alice.link(c,'pc');assert.notEqual(newPCId,pcId);
  await assertFails(gm.get('users/alice/characters/pc'));
  await gm.removeMember(c,'alice');
  assert.equal(await gm.get(`campaigns/${c}/pcs/${newPCId}`),null);
  assert.ok(await alice.get('users/alice/characters/pc'));
  await bob.removeMember(c,'bob');
  await gm.revoke(c);await assertFails(alice.invitation(replacement));
  await gm.deleteCampaign(c);
  assert.ok(await alice.get('users/alice/characters/pc'));
  assert.equal(await gm.get('users/gm/campaigns/'+c),null);
 } finally {stop?.();await env.cleanup();delete global.window;}
});
